In [1]:
import numpy as np
import pandas as pd

In [2]:
flats = pd.read_csv('flats_cleaned.csv')
houses = pd.read_csv('house_cleaned.csv')

In [4]:
flats.sample(1)

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
2128,6 BHK Flat in Sector 10A Gurgaon,flat,karmyogi apartment,2.3,6467.0,3557.0,Carpet area: 3556 (330.36 sq.m.),6,4,2,not available,"Sector 10A Gurgaon, Gurgaon, Haryana",6.0,NaN,5 to 10 Year Old,"['Rajiv Chowk Mosque', 'Gautam Hospital', 'Sai...",Prime location with park mandir and security w...,"['1 Exhaust Fan', '4 Light', 'No AC', 'No Bed'...",NaN,"['Environment4 out of 5', 'Lifestyle5 out of 5..."

In [5]:
houses.sample(1)

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
473,9 Bedroom House for sale in Palam Vihar Extension,house,independent,0.98,9074.0,1080.0,Carpet area: 120 (100.34 sq.m.),9,4,3,NaN,"40ft Road Near Rk Tower, Palam Vihar Extension...",1.0,South,undefined,NaN,9bhk residential house for resale in palam vih...,NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [6]:
df = pd.concat([flats,houses],ignore_index=True)

In [7]:
df = df.sample(df.shape[0],ignore_index=True)

In [8]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Sector 81 Gurgaon,flat,signature global synera,0.45,7525.0,598.0,Carpet area: 598 (55.56 sq.m.),2,2,2,store room,"011, Sector 81 Gurgaon, Gurgaon, Haryana",6.0,North-East,1 to 5 Year Old,"['Sapphire 83 Mall', 'Delhi Jaipur Expressway'...",Signature global is india's no.1 affordable ho...,"['3 Wardrobe', '3 Fan', '1 Exhaust Fan', '2 Ge...","['Power Back-up', 'Security / Fire Alarm', 'Li...","['Green Area4 out of 5', 'Construction3 out of..."
1,5 Bedroom House for sale in Sector 14 Gurgaon,house,independent,4.15,18444.0,2250.0,Plot area 250(209.03 sq.m.),5,4,2,NaN,"Sector 14 Gurgaon, Gurgaon, Haryana",2.0,North-West,10+ Year Old,"['Sheetla Mata Mandir', 'Hsbc bank ATM', 'Hdfc...",250 sqyds independent house for sale in sector...,"['5 Wardrobe', '8 Fan', '1 Exhaust Fan', '4 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
2,3 BHK Flat in Sector 71 Gurgaon,flat,chd avenue,1.40,7945.0,1762.0,Carpet area: 1762 (163.7 sq.m.),3,3,2,pooja room,"Sector 71 Gurgaon, Gurgaon, Haryana",1.0,South-East,5 to 10 Year Old,"['Huda City Centre', 'Apna Mart', 'Rajiv Chowk...",Beautiful made with with 2 side view and ample...,"['4 Wardrobe', '6 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Construction3 out of..."
3,9 Bedroom House for sale in Sector 47 Gurgaon,house,independent,5.15,26615.0,1935.0,Plot area 215(179.77 sq.m.),9,9,3+,store room,"02120, Sector 47 Gurgaon, Gurgaon, Haryana",3.0,East,1 to 5 Year Old,"['Standard chartered ATM', 'Icici bank ATM', '...",Corner 9bhk 215sq.Yd east facing independent f...,"['9 Wardrobe', '13 Fan', '1 Exhaust Fan', '23 ...","['High Ceiling Height', 'Maintenance Staff', '...","['Environment5 out of 5', 'Lifestyle4.5 out of..."
4,2 BHK Flat in Sohna,flat,global height,0.45,6338.0,710.0,Carpet area: 710 (65.96 sq.m.),2,2,2,not available,"Sohna, Gurgaon, Haryana",6.0,East,1 to 5 Year Old,NaN,Its totally ready to move properly and on highway,"['1 Water Purifier', '3 Fan', '1 Exhaust Fan',...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [9]:
df.to_csv('properties.csv',index=False)